package:
  name: libksba
  version: 1.3.3

source:
  fn: libksba-1.3.3.tar.bz2
  url: https://www.gnupg.org/ftp/gcrypt/libksba/libksba-1.3.3.tar.bz2
  sha256: 0c7f5ffe34d0414f6951d9880a46fcc2985c487f7c36369b9f11ad41131c7786

build:
  number: 0
  has_prefix_files:
    - bin/ksba-config
    - lib/libksba.la

requirements:
  build:
    - libgpg-error 1.19

  run:
    - libgpg-error 1.19
