package:
  name: libgpg-error
  version: 1.19

source:
  fn: libgpg-error-1.19.tar.bz2
  url: https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.19.tar.bz2
  sha256: 53120e1333d5c5d28d87ff2854e9e98719c8e214152f17ad5291704d25c4978b

build:
  number: 0
  has_prefix_files:
    - bin/gpg-error-config
    - lib/libgpg-error.la
