package:
  name: gpgme
  version: 1.5.5

source:
  fn: gpgme-1.5.5.tar.bz2
  url: https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.5.5.tar.bz2
  sha256: 0b3d3d5107680c594777aae65882a1ff6dd1ba629a83432e719c8b82a743c207

build:
  number: 0

requirements:
  build:
    - libgpg-error 1.19
    - libassuan 2.2.1
    - gnupg 2.1.7

  run:
    - libgpg-error 1.19
    - libassuan 2.2.1
    - gnupg 2.1.7
